### ISSUE TITLE
INFOGRAFIA HILOS

### ISSUE THREAD

**Issue by IsaacCS1** [SistemasTecTlaxiaco/infografia-de-hilos-IsaacCS1#2]
[INFOGRAFIA HILOS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-IsaacCS1/files/8395059/INFOGRAFIA.HILOS.pdf)

**Comment by IrvingFernand0** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
